namespace: pp
resources:
- ../../base
patchesStrategicMerge:
- templates/service.yaml
configMapGenerator:
- name: provider-configuration
  behavior: merge
  literals:
  - HELLO=Teja
  - ENV=PP
  - BACKGROUND_COLOR=yellow
  - RESPONSE_CODE=204