resources:
- templates/deployment.yaml
- templates/service.yaml
configMapGenerator:
- name: provider-configuration
  files:
  - application.properties
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated
