apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: provider-example
build:
  artifacts:
  - image: navyateja/provider-example
deploy:
  kustomize: {}
profiles:
  - name: Dev
    deploy:
      kustomize:
        paths:
        - environments/dev
    activation:
      - command: dev
  - name: PP
    deploy:
      kustomize:
        paths:
        - environments/pp
    activation:
      - command: pp
