apiVersion: skaffold/v1
kind: Config
metadata:
  name: provider-example
build:
  artifacts:
  - image: navyateja/provider-example
deploy:
  kustomize: {}
profiles:
  - name: Dev
    deploy:
      kustomize:
        flags:
          global: 
            - "--namespace dev"
    activation:
      - command: dev
  - name: PP
    deploy:
      kustomize:
        flags:
          global: 
            - "--namespace pp"
    activation:
      - command: pp
