
namespace: prod
resources:
- ../../base
patchesStrategicMerge:
- templates/service.yaml
configMapGenerator:
- name: provider-configuration
  behavior: merge
  literals:
  - IT_WORKS=false
  - ENV=prod
  - BACKGROUND_COLOR=red
  - RESPONSE_CODE=204
