apiVersion: v1
kind: Service
metadata:
  name: provider-nodeport
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30036
  selector:
    service: provider
  type: NodePort