name: Build and Deploy to GKE
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: skaffold build
      uses: navyatejaotturu-metronom/skaffold-action@v2
      with:
        skaffold: build 
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}

    - name: skaffold deploy
      uses: navyatejaotturu-metronom/skaffold-action@v2
      with:
        skaffold: build 
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}