
namespace: dev
resources:
- ../../base
patchesStrategicMerge:
- templates/service.yaml
configMapGenerator:
- name: provider-configuration
  behavior: merge
  literals:
  - IT_WORKS=false
  - ENV=dev
  - BACKGROUND_COLOR=red
